# Generated by Django 5.0 on 2024-07-02 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=60)),
                ('SchoolType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('level', models.CharField(max_length=60)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='school.school')),
            ],
        ),
    ]
